# All features below are unstable.
#
# This file is left as a reference, but commented out so it doesn't
# trip up stable `rustfmt`

#unstable_features = true

#group_imports = "StdExternalCrate"
#reorder_imports = true
#imports_indent = "Block"
#imports_layout = "HorizontalVertical"
#imports_granularity = "Module"

